### ISSUE TITLE
0.14.2 -b0 works fine with ESP32-S2mini.....

### ISSUE THREAD

**Issue by leonardocapone** [wled-install/wled-install.github.io#3]
Hi there, I'm looking for "0.14.2 -b0 Hoshi" bin file as it was perfectly working with a few ESP32 S2mini I have;
I manged to flash a couple but its seems that revsion is no longer available and all the available revisions I tried so far are not making the S2 mini working;
do you have any chance to share it?
thanks a lot in advance,
best regards!

**Comment by leonardocapone** [comment]
![ESP32 S2mini v0 14 2b0 hoshi](https://github.com/wled-install/wled-install.github.io/assets/114474756/46b11c75-8607-4edd-b9aa-c7dc5eb5ea4e)

**Comment by wled-install** [comment]
Check here in history if you can find it:
https://github.com/wled-install/wled-install.github.io/tree/gh-pages/bin_dir/1_Standard_version/Nightly_build

**Comment by leonardocapone** [comment]
thanks a lot;
I don't know if you can help...but it seems flashing from your alternative web installer did worked on a couple of ESP32 S2mini I had;
just recently I tried to flash a few more but it seems somthing is no longer allowing any bin file revision to run on the new S2mini I've got plus I reflash (fort testing) one of those which I got working and it looks like I can't get it back to work.

I can get the WLED only when I dowload both "adafruit-circuitpython-lolin_s2_mini-en_US-8.2.9.bin" (to partition 0x0) and the WLED bin file for S2 (any) to partition 0x10000;

the issue I've got is that whenever I tried to set it to my wifi network, it gets fine (I can get to its web interface) but when I reset it /reboot it it goes into WLED AP every single time.....it seems the saving of wifi network name and password is not really happening into the scriping.

that's pretty much it
thanks a lot for any help or suggestion you may want to give me.
have a good one!
L.

**Comment by leonardocapone** [comment]
fixed....thanks to your web installer! I missed the "oldmethod.html"...once selected it.....if flows without issues.

for my curiosity....would you please let me know what difference there's with it and how you think that affect ESP32-S2mini WLED installation?

thanks a lot again!!!

**Comment by wled-install** [comment]
oldmethod just uses older version of the esp-web-tool package that is responsible for web installation process. WLED software itself is the same.

**Comment by leonardocapone** [comment]
thanks! super clear!
I'm just wondering how that affect the bin flashing into the S2mini making them successfully working.
I'll try to dig into it to have a deeper understanding
thanks again!
